### ISSUE TITLE
Doesn't work with gnome-shell 3.10 (of course)

### ISSUE THREAD

**Issue by philn** [philn/gnome-shell-gajim-extension#12]
Gjs-Message: JS LOG: A TypeError has occured in gajim-contacts: this.searchSystem.pushResults is not a function
(gnome-shell:4184): Gjs-WARNING **: JS ERROR: Exception in callback for signal: NewMessage: TypeError: NotificationDaemon.NotificationApplicationPolicy is not a constructor
Source<._createPolicy@/home/phil/.local/share/gnome-shell/extensions/gajim@base-art.net/extension.js:168
wrapper@/usr/share/gjs-1.0/lang.js:213
Source<._init@/usr/share/gnome-shell/js/ui/messageTray.js:1310
wrapper@/usr/share/gjs-1.0/lang.js:213
_parent@/usr/share/gjs-1.0/lang.js:175
Source<._init@/home/phil/.local/share/gnome-shell/extensions/gajim@base-art.net/extension.js:76
wrapper@/usr/share/gjs-1.0/lang.js:213
_Base._construct@/usr/share/gjs-1.0/lang.js:154
Class._construct/newClass@/usr/share/gjs-1.0/lang.js:248
GajimExtension<._messageReceived@/home/phil/.local/share/gnome-shell/extensions/gajim@base-art.net/extension.js:742
wrapper@/usr/share/gjs-1.0/lang.js:213
@/home/phil/.local/share/gnome-shell/extensions/gajim@base-art.net/extension.js:713
_emit@/usr/share/gjs-1.0/signals.js:124
_convertToNativeSignal@/usr/share/gjs-1.0/overrides/Gio.js:130
